/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        outline: '#908fa0',
        'border-high': '#1F2937',
        error: '#ffb4ab',
        'tertiary-fixed-dim': '#ffb783',
        tertiary: '#ffb783',
        'on-primary': '#1000a9',
        'on-tertiary': '#4f2500',
        'text-primary': '#F9FAFB',
        'surface-bright': '#393841',
        'surface-dim': '#13131b',
        'surface-container-high': '#292932',
        'inverse-primary': '#494bd6',
        'on-tertiary-fixed': '#301400',
        'secondary-fixed': '#6ffbbe',
        'inverse-surface': '#e4e1ed',
        'surface-container-low': '#1b1b23',
        'on-surface-variant': '#c7c4d7',
        'on-error': '#690005',
        'on-tertiary-fixed-variant': '#703700',
        'secondary-fixed-dim': '#4edea3',
        'on-primary-container': '#0d0096',
        surface: '#13131b',
        'primary-fixed-dim': '#c0c1ff',
        'on-surface': '#e4e1ed',
        background: '#13131b',
        'on-primary-fixed-variant': '#2f2ebe',
        'border-low': '#111827',
        'surface-container-highest': '#34343d',
        'on-secondary-fixed': '#002113',
        'canvas-bg': '#000000',
        'surface-variant': '#34343d',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary-container': '#452000',
        'on-primary-fixed': '#07006c',
        primary: '#c0c1ff',
        'on-secondary': '#003824',
        'outline-variant': '#464554',
        'surface-zinc': 'rgba(9, 9, 11, 0.8)',
        'tertiary-container': '#d97721',
        'on-secondary-container': '#00311f',
        'surface-tint': '#c0c1ff',
        'inverse-on-surface': '#303038',
        secondary: '#4edea3',
        'primary-fixed': '#e1e0ff',
        'on-background': '#e4e1ed',
        'text-secondary': '#94A3B8',
        'on-error-container': '#ffdad6',
        'error-container': '#93000a',
        'surface-container-lowest': '#0d0d15',
        'primary-container': '#8083ff',
        'surface-container': '#1f1f27',
        'secondary-container': '#00a572',
        'tertiary-fixed': '#ffdcc5',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        unit: '4px',
        'card-padding': '24px',
        'container-max': '1280px',
        margin: '32px',
      },
      fontFamily: {
        'body-sm': ['Inter'],
        'technical-mono': ['Space Grotesk', 'monospace'],
        'headline-h3': ['Inter'],
        'headline-h2': ['Inter'],
        'body-base': ['Inter'],
        'headline-h1': ['Inter'],
        'technical-metric': ['Space Grotesk', 'monospace'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'technical-mono': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-h3': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-h2': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-base': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-h1': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'technical-metric': ['18px', { lineHeight: '1.0', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};